import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { migrateDatabaseAtPath, openDatabaseAtPath } from '../desktop/src/main/db/migrate'
import { createAssetRepository } from '../desktop/src/main/db/repositories/asset.repo'
import { classifyOrientation, createAssetPipeline } from '../desktop/src/main/assets/pipeline'
import { resolveAssetProtocolPath } from '../desktop/src/main/assets/protocol'

describe('M1 AssetService baseline', () => {
  it.each([
    [1024, 768, 'landscape'],
    [768, 1024, 'portrait'],
    [1024, 1024, 'square']
  ] as const)('classifies %dx%d as %s', (width, height, expected) => {
    expect(classifyOrientation(width, height)).toBe(expected)
  })

  it.each([
    [0, 768],
    [1024, 0],
    [-1, 768],
    [1024, Number.NaN]
  ])('rejects invalid dimensions %s x %s', (width, height) => {
    expect(() => classifyOrientation(width, height)).toThrow('asset_metadata_invalid')
  })

  it('saves generated bytes under the asset root and stores only relative paths', () => {
    const tempDir = mkdtempSync(join(tmpdir(), 'comiccanvas-assets-'))
    const dbPath = join(tempDir, 'assets.sqlite')
    const assetRoot = join(tempDir, 'assets')
    migrateDatabaseAtPath(dbPath)
    const db = openDatabaseAtPath(dbPath)

    try {
      const assets = createAssetRepository(db)
      const pipeline = createAssetPipeline({
        assetRoot,
        assets,
        idFactory: () => 'asset-1',
        clock: () => 1_782_500_000_000
      })
      const bytes = Uint8Array.from([1, 2, 3, 4, 5])

      const record = pipeline.saveGeneratedBytes({
        mediaType: 'image',
        bytes,
        metadata: {
          width: 1200,
          height: 800,
          mimeType: 'image/png'
        }
      })

      expect(record).toMatchObject({
        id: 'asset-1',
        mediaType: 'image',
        status: 'ready',
        relativePath: 'generated/image/7c/fdd07889b3295d6a550914ab35e068/generated-image-asset-1.png',
        safeUrl: 'cc-asset://asset/asset-1',
        metadata: {
          width: 1200,
          height: 800,
          orientation: 'landscape',
          mimeType: 'image/png',
          sizeBytes: 5,
          hash: '7cfdd07889b3295d6a550914ab35e068'
        }
      })
      expect(record.relativePath).not.toContain(':')
      expect(record.relativePath).not.toContain('..')
      expect(existsSync(join(assetRoot, record.relativePath))).toBe(true)
      expect(readFileSync(join(assetRoot, record.relativePath))).toEqual(Buffer.from(bytes))
      expect(assets.getById('asset-1')).toEqual(record)
    } finally {
      db.close()
      rmSync(tempDir, { recursive: true, force: true })
    }
  })

  it('resolves safe protocol URLs inside the asset root and rejects traversal', () => {
    const assetRoot = 'D:\\app-data\\ComicCanvas\\assets'
    const record = {
      id: 'asset-1',
      mediaType: 'image' as const,
      status: 'ready' as const,
      relativePath: 'generated/image/74/f039f60f7ac1247ac6fbe8a15e56a6/generated-image-asset-1.png',
      safeUrl: 'cc-asset://asset/asset-1',
      metadata: {},
      createdAt: 1,
      updatedAt: 1
    }

    expect(resolveAssetProtocolPath(assetRoot, record)).toBe(
      'D:\\app-data\\ComicCanvas\\assets\\generated\\image\\74\\f039f60f7ac1247ac6fbe8a15e56a6\\generated-image-asset-1.png'
    )
    expect(() => resolveAssetProtocolPath(assetRoot, { ...record, relativePath: '..\\secret.txt' })).toThrow('asset_path_traversal')
    expect(() => resolveAssetProtocolPath(assetRoot, { ...record, relativePath: 'C:\\secret.txt' })).toThrow('asset_path_traversal')
  })
})
