import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateDatabaseAtPath, openDatabaseAtPath } from '../desktop/src/main/db/migrate';
import { createAssetRepository } from '../desktop/src/main/db/repositories/asset.repo';
import { classifyOrientation, createAssetPipeline } from '../desktop/src/main/assets/pipeline';
import { resolveAssetProtocolPath } from '../desktop/src/main/assets/protocol';
import { inferImportedAssetMetadata } from '../desktop/src/main/assets/import-metadata';
describe('M1 AssetService baseline', () => {
    it.each([
        [1024, 768, 'landscape'],
        [768, 1024, 'portrait'],
        [1024, 1024, 'square']
    ])('classifies %dx%d as %s', (width, height, expected) => {
        expect(classifyOrientation(width, height)).toBe(expected);
    });
    it.each([
        [0, 768],
        [1024, 0],
        [-1, 768],
        [1024, Number.NaN]
    ])('rejects invalid dimensions %s x %s', (width, height) => {
        expect(() => classifyOrientation(width, height)).toThrow('asset_metadata_invalid');
    });
    it('saves generated bytes under the asset root and stores only relative paths', () => {
        const tempDir = mkdtempSync(join(tmpdir(), 'comiccanvas-assets-'));
        const dbPath = join(tempDir, 'assets.sqlite');
        const assetRoot = join(tempDir, 'assets');
        migrateDatabaseAtPath(dbPath);
        const db = openDatabaseAtPath(dbPath);
        try {
            const assets = createAssetRepository(db);
            const pipeline = createAssetPipeline({
                assetRoot,
                assets,
                idFactory: () => 'asset-1',
                clock: () => 1_782_500_000_000
            });
            const bytes = Uint8Array.from([1, 2, 3, 4, 5]);
            const record = pipeline.saveGeneratedBytes({
                mediaType: 'image',
                bytes,
                metadata: {
                    width: 1200,
                    height: 800,
                    mimeType: 'image/png'
                }
            });
            expect(record).toMatchObject({
                id: 'asset-1',
                mediaType: 'image',
                status: 'ready',
                relativePath: 'generated/image/7c/fdd07889b3295d6a550914ab35e068/generated-image-asset-1.png',
                safeUrl: 'cc-asset://asset/asset-1',
                metadata: {
                    width: 1200,
                    height: 800,
                    orientation: 'landscape',
                    mimeType: 'image/png',
                    sizeBytes: 5,
                    hash: '7cfdd07889b3295d6a550914ab35e068'
                }
            });
            expect(record.relativePath).not.toContain(':');
            expect(record.relativePath).not.toContain('..');
            expect(existsSync(join(assetRoot, record.relativePath))).toBe(true);
            expect(readFileSync(join(assetRoot, record.relativePath))).toEqual(Buffer.from(bytes));
            expect(assets.getById('asset-1')).toEqual(record);
        }
        finally {
            db.close();
            rmSync(tempDir, { recursive: true, force: true });
        }
    });
    it('extracts imported PNG dimensions, orientation, hash, and size', () => {
        const bytes = Buffer.alloc(24);
        Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(bytes, 0);
        bytes.writeUInt32BE(1200, 16);
        bytes.writeUInt32BE(800, 20);
        expect(inferImportedAssetMetadata({
            mediaType: 'image',
            bytes,
            mimeType: 'image/png',
            sizeBytes: bytes.byteLength
        })).toMatchObject({
            width: 1200,
            height: 800,
            orientation: 'landscape',
            mimeType: 'image/png',
            sizeBytes: 24
        });
    });
    it('extracts best-effort audio duration from constant-bitrate MP3 frames', () => {
        const bytes = Buffer.alloc(48);
        Buffer.from([0xff, 0xfb, 0x90, 0x64]).copy(bytes, 0);
        expect(inferImportedAssetMetadata({
            mediaType: 'audio',
            bytes,
            mimeType: 'audio/mpeg',
            sizeBytes: bytes.byteLength
        })).toMatchObject({
            durationMs: 3,
            mimeType: 'audio/mpeg',
            sizeBytes: 48
        });
    });
    it('resolves safe protocol URLs inside the asset root and rejects traversal', () => {
        const assetRoot = join(tmpdir(), 'comiccanvas-assets-root');
        const record = {
            id: 'asset-1',
            mediaType: 'image',
            status: 'ready',
            relativePath: 'generated/image/74/f039f60f7ac1247ac6fbe8a15e56a6/generated-image-asset-1.png',
            safeUrl: 'cc-asset://asset/asset-1',
            metadata: {},
            createdAt: 1,
            updatedAt: 1
        };
        expect(resolveAssetProtocolPath(assetRoot, record)).toBe(join(assetRoot, record.relativePath));
        expect(() => resolveAssetProtocolPath(assetRoot, { ...record, relativePath: '..\\secret.txt' })).toThrow('asset_path_traversal');
        expect(() => resolveAssetProtocolPath(assetRoot, { ...record, relativePath: '/secret.txt' })).toThrow('asset_path_traversal');
    });
});
